" /*"
" **"
" ** Bits in the bitfield 'permit':"
" **  Bit 0: foot"
" **  Bit 1: bike"
" **  Bit 2: car"
" **  Bit 3: paved"
" **  Bit 4: oneway_bike"
" **  Bit 5: oneway_car"
" **  Bit 6: (not used)"
" **  Bit 7: (not used)"
" **"
" */"
" BEGIN TRANSACTION;"
" CREATE TABLE graph_permit(\n"
"   key       TEXT,     -- tag key\n"
"   value     TEXT,     -- tag value\n"
"   set_bit   INTEGER,  -- bitmask set bits\n"
"   clear_bit INTEGER   -- bitmask clear bits\n"
" );\n"
" /*"
" ** Tags to set permit bits"
" */"
" /* Tags foot -> set bit 0, mask 00000001 dec 1 */"
" INSERT INTO graph_permit VALUES ('highway','footway',               1, 255);"
" INSERT INTO graph_permit VALUES ('highway','pedestrian',            1, 255);"
" INSERT INTO graph_permit VALUES ('highway','residential',           1, 255);"
" INSERT INTO graph_permit VALUES ('highway','living_street',         1, 255);"
" INSERT INTO graph_permit VALUES ('highway','service',               1, 255);"
" INSERT INTO graph_permit VALUES ('highway','unclassified',          1, 255);"
" INSERT INTO graph_permit VALUES ('highway','track',                 1, 255);"
" INSERT INTO graph_permit VALUES ('highway','steps',                 1, 255);"
" INSERT INTO graph_permit VALUES ('highway','path',                  1, 255);"
" INSERT INTO graph_permit VALUES ('highway','construction',          1, 255);"
" INSERT INTO graph_permit VALUES ('foot','yes',                      1, 255);"
" INSERT INTO graph_permit VALUES ('foot','designated',               1, 255);"
" INSERT INTO graph_permit VALUES ('sidewalk','both',                 1, 255);"
" INSERT INTO graph_permit VALUES ('sidewalk:both','yes',             1, 255);"
" INSERT INTO graph_permit VALUES ('sidewalk','right',                1, 255);"
" INSERT INTO graph_permit VALUES ('sidewalk:right','yes',            1, 255);"
" INSERT INTO graph_permit VALUES ('sidewalk','left',                 1, 255);"
" INSERT INTO graph_permit VALUES ('sidewalk:left','yes',             1, 255);"
" INSERT INTO graph_permit VALUES ('sidewalk','yes',                  1, 255);"
" /* Tags bike -> set bit 1, mask 00000010 dec 2 */"
" INSERT INTO graph_permit VALUES ('highway','cycleway',              2, 255);"
" INSERT INTO graph_permit VALUES ('highway','residential',           2, 255);"
" INSERT INTO graph_permit VALUES ('highway','living_street',         2, 255);"
" INSERT INTO graph_permit VALUES ('highway','service',               2, 255);"
" INSERT INTO graph_permit VALUES ('highway','track',                 2, 255);"
" INSERT INTO graph_permit VALUES ('highway','unclassified',          2, 255);"
" INSERT INTO graph_permit VALUES ('highway','tertiary',              2, 255);"
" INSERT INTO graph_permit VALUES ('highway','tertiary_link',         2, 255);"
" INSERT INTO graph_permit VALUES ('highway','secondary',             2, 255);"
" INSERT INTO graph_permit VALUES ('highway','secondary_link',        2, 255);"
" INSERT INTO graph_permit VALUES ('cycleway','track',                2, 255);"
" INSERT INTO graph_permit VALUES ('cycleway:right','track',          2, 255);"
" INSERT INTO graph_permit VALUES ('cycleway','lane',                 2, 255);"
" INSERT INTO graph_permit VALUES ('cycleway:right','lane',           2, 255);"
" INSERT INTO graph_permit VALUES ('bicycle','designated',            2, 255);"
" INSERT INTO graph_permit VALUES ('bicycle','yes',                   2, 255);"
" /* Tags car -> set bit 2, mask  00000100 dec 4 */"
" INSERT INTO graph_permit VALUES ('highway','unclassified',          4, 255);"
" INSERT INTO graph_permit VALUES ('highway','residential',           4, 255);"
" INSERT INTO graph_permit VALUES ('highway','tertiary',              4, 255);"
" INSERT INTO graph_permit VALUES ('highway','tertiary_link',         4, 255);"
" INSERT INTO graph_permit VALUES ('highway','secondary',             4, 255);"
" INSERT INTO graph_permit VALUES ('highway','secondary_link',        4, 255);"
" INSERT INTO graph_permit VALUES ('highway','primary',               4, 255);"
" INSERT INTO graph_permit VALUES ('highway','primary_link',          4, 255);"
" INSERT INTO graph_permit VALUES ('highway','trunk',                 4, 255);"
" INSERT INTO graph_permit VALUES ('highway','trunk_link',            4, 255);"
" INSERT INTO graph_permit VALUES ('highway','motorway',              4, 255);"
" INSERT INTO graph_permit VALUES ('highway','motorway_link',         4, 255);"
" /* Tags paved -> set bit 3, mask 00001000 dec 8 */"
" INSERT INTO graph_permit VALUES ('surface','asphalt',               8, 255);"
" INSERT INTO graph_permit VALUES ('surface','sett',                  8, 255);"
" INSERT INTO graph_permit VALUES ('surface','paving_stones',         8, 255);"
" /* Tags oneway -> set bits 4 and 5, mask  00110000 dec 48 */"
" INSERT INTO graph_permit VALUES ('oneway','yes',                   48, 255);"
" /*"
" ** Tags to clear permit bits"
" */"
" /* Tags no foot -> clear bits 11111110 (dec 254) */"
" INSERT INTO graph_permit VALUES ('sidewalk','separate',             0, 254);"
" INSERT INTO graph_permit VALUES ('foot','use_sidepath',             0, 254);"
" INSERT INTO graph_permit VALUES ('access','no',                     0, 254);"
" /* Tags no bike -> clear bits 11111101 (dec 253) */"
" INSERT INTO graph_permit VALUES ('cycleway','separate',             0, 253);"
" INSERT INTO graph_permit VALUES ('cycleway:both','separate',        0, 253);"
" INSERT INTO graph_permit VALUES ('cycleway:right','separate',       0, 253);"
" INSERT INTO graph_permit VALUES ('cycleway:left','separate',        0, 253);"
" INSERT INTO graph_permit VALUES ('bicycle','use_sidepath',          0, 253);"
" INSERT INTO graph_permit VALUES ('access','no',                     0, 253);"
" /* Tags no oneway -> clear bits 11101111 (dec 239) */"
" INSERT INTO graph_permit VALUES ('oneway:bicycle','no',             0, 239);"
" /* create index */"
" CREATE INDEX graph_permit__key_value ON graph_permit (key, value);"
" COMMIT TRANSACTION;"
