" /*"
" **"
" ** Bits in the bitfield 'permit':"
" **  Bit 0: foot"
" **  Bit 1: bike"
" **  Bit 2: car"
" **  Bit 3: paved"
" **  Bit 4: oneway_bike"
" **  Bit 5: oneway_car"
" **  Bit 6: (not used)"
" **  Bit 7: (not used)"
" **"
" */"
" BEGIN TRANSACTION;"
" CREATE TABLE graph_permit(\n"
"   key       TEXT,     -- tag key\n"
"   value     TEXT,     -- tag value\n"
"   set_bit   INTEGER,  -- bitmask set bits\n"
"   clear_bit INTEGER   -- bitmask clear bits\n"
" );\n"
" /*"
" ** Tags to set permit bits"
" */"
" /* Tags that allow access for foot, bike or car */"
" INSERT INTO graph_permit VALUES ('highway','motorway',              4, 255);"
" INSERT INTO graph_permit VALUES ('highway','motorway_link',         4, 255);"
" INSERT INTO graph_permit VALUES ('highway','trunk',                 4, 255);"
" INSERT INTO graph_permit VALUES ('highway','trunk_link',            4, 255);"
" INSERT INTO graph_permit VALUES ('highway','primary',               4, 255);"
" INSERT INTO graph_permit VALUES ('highway','primary_link',          4, 255);"
" INSERT INTO graph_permit VALUES ('highway','secondary',             6, 255);"
" INSERT INTO graph_permit VALUES ('highway','secondary_link',        6, 255);"
" INSERT INTO graph_permit VALUES ('highway','tertiary',              6, 255);"
" INSERT INTO graph_permit VALUES ('highway','tertiary_link',         6, 255);"
" INSERT INTO graph_permit VALUES ('highway','unclassified',          7, 255);"
" INSERT INTO graph_permit VALUES ('highway','residential',           7, 255);"
" INSERT INTO graph_permit VALUES ('highway','living_street',         7, 255);"
" INSERT INTO graph_permit VALUES ('highway','service',               7, 255);"
" INSERT INTO graph_permit VALUES ('highway','pedestrian',            1, 255);"
" INSERT INTO graph_permit VALUES ('highway','track',                 3, 255);"
" INSERT INTO graph_permit VALUES ('highway','footway',               1, 255);"
" INSERT INTO graph_permit VALUES ('highway','steps',                 1, 255);"
" INSERT INTO graph_permit VALUES ('highway','path',                  1, 255);"
" INSERT INTO graph_permit VALUES ('highway','construction',          1, 255);"
" INSERT INTO graph_permit VALUES ('footway','sidewalk',              1, 255);"
" INSERT INTO graph_permit VALUES ('foot','yes',                      1, 255);"
" INSERT INTO graph_permit VALUES ('foot','designated',               1, 255);"
" INSERT INTO graph_permit VALUES ('sidewalk','both',                 1, 255);"
" INSERT INTO graph_permit VALUES ('sidewalk:both','yes',             1, 255);"
" INSERT INTO graph_permit VALUES ('sidewalk','right',                1, 255);"
" INSERT INTO graph_permit VALUES ('sidewalk:right','yes',            1, 255);"
" INSERT INTO graph_permit VALUES ('sidewalk','left',                 1, 255);"
" INSERT INTO graph_permit VALUES ('sidewalk:left','yes',             1, 255);"
" INSERT INTO graph_permit VALUES ('sidewalk','yes',                  1, 255);"
" INSERT INTO graph_permit VALUES ('highway','cycleway',              2, 255);"
" INSERT INTO graph_permit VALUES ('cycleway','track',                2, 255);"
" INSERT INTO graph_permit VALUES ('cycleway:right','track',          2, 255);"
" INSERT INTO graph_permit VALUES ('cycleway','lane',                 2, 255);"
" INSERT INTO graph_permit VALUES ('cycleway:right','lane',           2, 255);"
" INSERT INTO graph_permit VALUES ('bicycle','designated',            2, 255);"
" INSERT INTO graph_permit VALUES ('bicycle','yes',                   2, 255);"
" /* Tags that show paved roads */"
" INSERT INTO graph_permit VALUES ('surface','asphalt',               8, 255);"
" INSERT INTO graph_permit VALUES ('surface','sett',                  8, 255);"
" INSERT INTO graph_permit VALUES ('surface','paving_stones',         8, 255);"
" /* Tags that show one way */"
" INSERT INTO graph_permit VALUES ('oneway','yes',                   48, 255);"
" /*"
" ** Tags to clear permit bits"
" */"
" INSERT INTO graph_permit VALUES ('access','no',                     0, 248);"
" /* Tags no foot */"
" INSERT INTO graph_permit VALUES ('sidewalk','separate',             0, 254);"
" INSERT INTO graph_permit VALUES ('sidewalk:both','separate',        0, 254);"
" INSERT INTO graph_permit VALUES ('foot','use_sidepath',             0, 254);"
" INSERT INTO graph_permit VALUES ('foot','no',                       0, 254);"
" /* Tags no bike */"
" INSERT INTO graph_permit VALUES ('cycleway','separate',             0, 253);"
" INSERT INTO graph_permit VALUES ('cycleway:both','separate',        0, 253);"
" INSERT INTO graph_permit VALUES ('bicycle','use_sidepath',          0, 253);"
" INSERT INTO graph_permit VALUES ('bicycle','no',                    0, 253);"
" /* Tags no car */"
" INSERT INTO graph_permit VALUES ('motor_vehicle','no',              0, 251);"
" INSERT INTO graph_permit VALUES ('motor_vehicle','forestry',        0, 251);"
" INSERT INTO graph_permit VALUES ('motorcar','no',                   0, 251);"
" /* Tags no oneway bike */"
" INSERT INTO graph_permit VALUES ('oneway:bicycle','no',             0, 239);"
" /*"
" ** Create index"
" */"
" CREATE INDEX graph_permit__key_value ON graph_permit (key, value);"
" COMMIT TRANSACTION;"
