/*
** Functions for creating an HTML file with Leaflet.js for visualizing data
*/

void leaflet_html_header(FILE *html, const char *title) {
  fprintf(html,
    "<!DOCTYPE html>\n"
    "<html>\n"
    "<head>\n"
    "  <title>%s</title>\n"
    "  <meta charset=\"utf-8\" />\n"
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
    "  <link rel=\"stylesheet\" href=\"https://unpkg.com/leaflet@1.9.4/dist/leaflet.css\" integrity=\"sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=\" crossorigin=\"\"/>\n"
    "  <script src=\"https://unpkg.com/leaflet@1.9.4/dist/leaflet.js\" integrity=\"sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=\" crossorigin=\"\"></script>\n"
    "  <style>\n"
    "  .leaflet-container {\n"
    "    width: 850px;\n"
    "    height: 300px;\n"
    "    margin-bottom: 10px;\n"
    "  }\n"
    "  body {\n"
    "   font-family: Verdana, Arial;\n"
    "   font-size: 1.0em;\n"
    "   color: #bbbbbb;\n"
    "   background: #333333;\n"
    "  }\n"
    "  table {\n"
    "   border: 2px solid #777777;\n"
    "   border-collapse: collapse;\n"
    "  }\n"
    "  th {\n"
    "   border: 1px solid #777777;\n"
    "   background: #555555;\n"
    "  }\n"
    "  td {\n"
    "   border: 1px solid #555588;\n"
    "   padding-left: 3px;\n"
    "   padding-right: 2px;\n"
    "  }\n"
    "  a {\n"
    "   color: #68B0FD;\n"
    "  }\n"
    "  </style>\n"
    "</head>\n"
    "<body>\n", title
  );
}

void leaflet_html_footer(FILE *html) {
  fprintf(html,
    "<hr>\n"
    "<p>Generated by pbf2sqlite " PBF2SQLITE_VERSION "</p>\n"
    "</body>\n"
    "</html>"
  );
}

void leaflet_init(
  FILE *html,
  const char *mapid,
  const double lon1,
  const double lat1,
  const double lon2,
  const double lat2
){
  fprintf(html, "// %s init\n", mapid);
  fprintf(html, "const %s = L.map('%s').fitBounds([ [%.7f, %.7f], [%.7f, %.7f] ], "
                "{padding: [0,0], maxZoom: 19});\n",
                 mapid, mapid, lat1, lon1, lat2, lon2);
  fprintf(html, "L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', "
                "{maxZoom:19}).addTo(%s);\n", mapid);
  fprintf(html, "L.control.scale({ position: 'bottomleft', maxWidth: 200, "
                "metric:true, imperial:false }).addTo(%s);\n", mapid);
  fprintf(html, "var %s_popup = L.popup();\n", mapid);
  fprintf(html, "function %s_map_click(e) {\n"
            "  var geo = e.latlng;\n"
            "  var lat = geo.lat;\n"
            "  var lon = geo.lng;\n"
            "  lat = lat.toFixed(7);\n"
            "  lon = lon.toFixed(7);\n"
            "  var popuptext = '<pre>lon(x)    lat(y)<br>'+lon+' '+lat+'<br></pre>';\n"
            "  %s_popup.setLatLng(e.latlng).setContent(popuptext).openOn(%s);\n"
            "}\n", mapid, mapid, mapid);
  fprintf(html, "%s.on('click', %s_map_click);\n", mapid, mapid);
  fprintf(html, "var style = { color:'#0000ff', opacity:0.5, weight:4, "
                "dashArray:'none', fillColor:'#ff7800', fillOpacity:0.5 };\n");
}

void leaflet_marker(
  FILE *html,
  const char *mapid,
  const double lon,
  const double lat,
  const char *text
){
  fprintf(html, "L.marker([%.7f, %.7f]).addTo(%s)", lat, lon, mapid);
  if( text[0]!='\0' ) fprintf(html, ".bindPopup(\"%s\")", text);
  fprintf(html, ";\n");
}

void leaflet_polyline(
  FILE *html,
  const char *mapid,
  point *pointlist,
  const char *text
){
  fprintf(html, "L.polyline( [\n");
  for(int i=0; i<pointlist[0].no; i++){
    if( i>0 ) fprintf(html, ",\n");
    fprintf(html, "[%.7f, %.7f]", pointlist[i].lat, pointlist[i].lon);
  }
  fprintf(html, " ], style).addTo(%s)",  mapid);
  if( text[0]!='\0' ) fprintf(html, ".bindPopup(\"%s\")", text);
  fprintf(html, ";\n");
}

void leaflet_line(
  FILE *html,
  const char *mapid,
  const double lon1,
  const double lat1,
  const double lon2,
  const double lat2,
  const char *text
){
  fprintf(html, "L.polyline([ [%.7f, %.7f], [%.7f, %.7f] ]).addTo(%s)",
          lat1, lon1, lat2, lon2, mapid);
  if( text[0]!='\0' ) fprintf(html, ".bindPopup(\"%s\")", text);
  fprintf(html, ";\n");
}

void leaflet_polygon(
  FILE *html,
  const char *mapid,
  point *pointlist,
  const char *text
){
  fprintf(html, "L.polygon( [\n");
  for(int i=0; i<pointlist[0].no; i++){
    if( i>0 ) fprintf(html, ",\n");
    fprintf(html, "[%.7f, %.7f]", pointlist[i].lat, pointlist[i].lon);
  }
  fprintf(html, " ], style).addTo(%s)",  mapid);
  if( text[0]!='\0' ) fprintf(html, ".bindPopup(\"%s\")", text);
  fprintf(html, ";\n");
}

void leaflet_circle(
  FILE *html,
  const char *mapid,
  const double lon,
  const double lat,
  const int radius,
  const char *text
){
  fprintf(html, "L.circle([%.7f, %.7f], %d, style).addTo(%s)", lat, lon, radius, mapid);
  if( text[0]!='\0' ) fprintf(html, ".bindPopup(\"%s\")", text);
  fprintf(html, ";\n");
}

void leaflet_circlemarker(
  FILE *html,
  const char *mapid,
  const double lon,
  const double lat,
  const char *text
){
  fprintf(html, "L.circleMarker([%.7f, %.7f], style).addTo(%s)", lat, lon,  mapid);
  if( text[0]!='\0' ) fprintf(html, ".bindPopup(\"%s\")", text);
  fprintf(html, ";\n");
}

void leaflet_rectangle(
  FILE *html,
  const char *mapid,
  const double lon1,
  const double lat1,
  const double lon2,
  const double lat2,
  const char *text
){
  fprintf(html, "L.rectangle([[%.7f, %.7f], [%.7f, %.7f]], style).addTo(%s)", lat1, lon1, lat2, lon2, mapid);
  if( text[0]!='\0' ) fprintf(html, ".bindPopup(\"%s\")", text);
  fprintf(html, ";\n");
}

void leaflet_style(
  FILE *html,
  const char *color,
  const double opacity,
  const int weight,
  const char *dasharray,
  const char *fillcolor,
  const double fillopacity,
  const int radius
){
  fprintf(html,
    "style = { color:'%s', opacity:%f, weight:%d, dashArray:'%s', fillColor:'%s', "
    "fillOpacity:%f, radius:%d };\n", color, opacity, weight, dasharray, fillcolor, fillopacity, radius);
}

